name: Deploy Coin-market
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Check node and npm
        run: |
          node -v
          npm -v